// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railroad.DAL.Data;

#nullable disable

namespace Railroad.Migrations
{
    [DbContext(typeof(RailroadDbContext))]
    [Migration("20250923114101_wtf")]
    partial class wtf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Railroad.DAL.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountValue")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountValue")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountValue = 10,
                            Email = "ivan@mail.com",
                            PersonId = 1,
                            RegistrationDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DiscountValue = 5,
                            Email = "olena@mail.com",
                            PersonId = 2,
                            RegistrationDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DiscountValue = 15,
                            Email = "serhiy@mail.com",
                            PersonId = 3,
                            RegistrationDate = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DiscountValue = 7,
                            Email = "kateryna@mail.com",
                            PersonId = 4,
                            RegistrationDate = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DiscountValue = 12,
                            Email = "mykola@mail.com",
                            PersonId = 5,
                            RegistrationDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DiscountValue = 3,
                            Email = "oksana@mail.com",
                            PersonId = 6,
                            RegistrationDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Kyiv",
                            Country = "Ukraine",
                            Name = "Ivan",
                            PhoneNumber = "380931234567",
                            Surname = "Petrenko"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lviv",
                            Country = "Ukraine",
                            Name = "Olena",
                            PhoneNumber = "380671112233",
                            Surname = "Shevchenko"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Odesa",
                            Country = "Ukraine",
                            Name = "Serhiy",
                            PhoneNumber = "380501234567",
                            Surname = "Koval"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1992, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Dnipro",
                            Country = "Ukraine",
                            Name = "Kateryna",
                            PhoneNumber = "380631112233",
                            Surname = "Bondarenko"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1985, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Kharkiv",
                            Country = "Ukraine",
                            Name = "Mykola",
                            PhoneNumber = "380671223344",
                            Surname = "Shevtsov"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1998, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Vinnytsia",
                            Country = "Ukraine",
                            Name = "Oksana",
                            PhoneNumber = "380931556677",
                            Surname = "Moroz"
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PriceForKGOfCarriageWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceForKilometer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PriceForKGOfCarriageWeight = 2.5m,
                            PriceForKilometer = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            PriceForKGOfCarriageWeight = 3m,
                            PriceForKilometer = 0.55m
                        },
                        new
                        {
                            Id = 3,
                            PriceForKGOfCarriageWeight = 2.2m,
                            PriceForKilometer = 0.45m
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceFromPreviousStation")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("TrainRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainRouteId");

                    b.ToTable("RoutePoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2025, 8, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 0.0,
                            Order = 1,
                            Platform = 1,
                            StationId = 1,
                            TrainRouteId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2025, 8, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 130.0,
                            Order = 2,
                            Platform = 1,
                            StationId = 8,
                            TrainRouteId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2025, 8, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 180.0,
                            Order = 3,
                            Platform = 2,
                            StationId = 7,
                            TrainRouteId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2025, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 220.0,
                            Order = 4,
                            Platform = 2,
                            StationId = 2,
                            TrainRouteId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2025, 8, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 0.0,
                            Order = 1,
                            Platform = 1,
                            StationId = 2,
                            TrainRouteId = 2
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2025, 8, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 250.0,
                            Order = 2,
                            Platform = 2,
                            StationId = 6,
                            TrainRouteId = 2
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2025, 8, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 180.0,
                            Order = 3,
                            Platform = 2,
                            StationId = 8,
                            TrainRouteId = 2
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2025, 8, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 28, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 200.0,
                            Order = 4,
                            Platform = 3,
                            StationId = 3,
                            TrainRouteId = 2
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new DateTime(2025, 8, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 29, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 0.0,
                            Order = 1,
                            Platform = 1,
                            StationId = 3,
                            TrainRouteId = 3
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new DateTime(2025, 8, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 29, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 400.0,
                            Order = 2,
                            Platform = 1,
                            StationId = 4,
                            TrainRouteId = 3
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = new DateTime(2025, 8, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 29, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 320.0,
                            Order = 3,
                            Platform = 2,
                            StationId = 9,
                            TrainRouteId = 3
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = new DateTime(2025, 8, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 29, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 600.0,
                            Order = 4,
                            Platform = 3,
                            StationId = 5,
                            TrainRouteId = 3
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = new DateTime(2025, 8, 30, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 30, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 0.0,
                            Order = 1,
                            Platform = 1,
                            StationId = 4,
                            TrainRouteId = 4
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = new DateTime(2025, 8, 30, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 30, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 300.0,
                            Order = 2,
                            Platform = 2,
                            StationId = 9,
                            TrainRouteId = 4
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = new DateTime(2025, 8, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 30, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 250.0,
                            Order = 3,
                            Platform = 2,
                            StationId = 8,
                            TrainRouteId = 4
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = new DateTime(2025, 8, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 30, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 500.0,
                            Order = 4,
                            Platform = 1,
                            StationId = 1,
                            TrainRouteId = 4
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = new DateTime(2025, 8, 31, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 31, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 0.0,
                            Order = 1,
                            Platform = 1,
                            StationId = 6,
                            TrainRouteId = 5
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = new DateTime(2025, 8, 31, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 31, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 180.0,
                            Order = 2,
                            Platform = 2,
                            StationId = 7,
                            TrainRouteId = 5
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = new DateTime(2025, 8, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 31, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 130.0,
                            Order = 3,
                            Platform = 2,
                            StationId = 8,
                            TrainRouteId = 5
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = new DateTime(2025, 8, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2025, 8, 31, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            DistanceFromPreviousStation = 400.0,
                            Order = 4,
                            Platform = 3,
                            StationId = 2,
                            TrainRouteId = 5
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NuberOfPlatforms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Kyiv",
                            DistrictName = "Podil",
                            Name = "Central Station",
                            NuberOfPlatforms = 5
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Lviv",
                            DistrictName = "Halych",
                            Name = "South Station",
                            NuberOfPlatforms = 3
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Odesa",
                            DistrictName = "Primorsky",
                            Name = "North Station",
                            NuberOfPlatforms = 4
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Dnipro",
                            DistrictName = "Novokodatsky",
                            Name = "East Station",
                            NuberOfPlatforms = 2
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Kharkiv",
                            DistrictName = "Kholodnohirsk",
                            Name = "West Station",
                            NuberOfPlatforms = 3
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Vinnytsia",
                            DistrictName = "Center",
                            Name = "Central Vinnytsia",
                            NuberOfPlatforms = 2
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Cherkasy",
                            DistrictName = "Center",
                            Name = "Cherkasy Station",
                            NuberOfPlatforms = 2
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Zhytomyr",
                            DistrictName = "Center",
                            Name = "Zhytomyr Station",
                            NuberOfPlatforms = 2
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Poltava",
                            DistrictName = "Center",
                            Name = "Poltava Station",
                            NuberOfPlatforms = 2
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<decimal>("CarriagePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CarriageWeight")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RoadPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<int>("TrainRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PriceId");

                    b.HasIndex("TrainRouteId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarriagePrice = 25m,
                            CarriageWeight = 10.0,
                            CustomerId = 1,
                            DepartureStationId = 1,
                            DestinationStationId = 2,
                            FinalPrice = 295m,
                            PriceId = 1,
                            PurchaseDate = new DateTime(2024, 9, 12, 5, 2, 3, 0, DateTimeKind.Unspecified),
                            RoadPrice = 270m,
                            Seat = 12,
                            TrainRouteId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarriagePrice = 37.5m,
                            CarriageWeight = 15.0,
                            CustomerId = 2,
                            DepartureStationId = 2,
                            DestinationStationId = 3,
                            FinalPrice = 307.5m,
                            PriceId = 1,
                            PurchaseDate = new DateTime(2025, 8, 28, 9, 1, 1, 0, DateTimeKind.Unspecified),
                            RoadPrice = 270m,
                            Seat = 8,
                            TrainRouteId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarriagePrice = 30m,
                            CarriageWeight = 12.0,
                            CustomerId = 3,
                            DepartureStationId = 8,
                            DestinationStationId = 1,
                            FinalPrice = 300m,
                            PriceId = 1,
                            PurchaseDate = new DateTime(2024, 7, 28, 8, 11, 12, 0, DateTimeKind.Unspecified),
                            RoadPrice = 270m,
                            Seat = 9,
                            TrainRouteId = 1
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intercity-1",
                            NumberOfSeats = 200
                        },
                        new
                        {
                            Id = 2,
                            Name = "Express-5",
                            NumberOfSeats = 150
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rapid-3",
                            NumberOfSeats = 180
                        },
                        new
                        {
                            Id = 4,
                            Name = "Local-2",
                            NumberOfSeats = 100
                        },
                        new
                        {
                            Id = 5,
                            Name = "NightLine-7",
                            NumberOfSeats = 220
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.TrainRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kyiv - Lviv Route",
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lviv - Odesa Route",
                            TrainId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odesa - Kharkiv Route",
                            TrainId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dnipro - Kyiv Route",
                            TrainId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vinnytsia - Lviv Route",
                            TrainId = 5
                        });
                });

            modelBuilder.Entity("Railroad.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Admin", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Customer", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.RoutePoint", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railroad.DAL.Entities.TrainRoute", "TrainRoute")
                        .WithMany("RoutePoints")
                        .HasForeignKey("TrainRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("TrainRoute");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Ticket", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Admin", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AdminId");

                    b.HasOne("Railroad.DAL.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railroad.DAL.Entities.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railroad.DAL.Entities.TrainRoute", "TrainRoute")
                        .WithMany()
                        .HasForeignKey("TrainRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Price");

                    b.Navigation("TrainRoute");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.TrainRoute", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.User", b =>
                {
                    b.HasOne("Railroad.DAL.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Admin", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Railroad.DAL.Entities.TrainRoute", b =>
                {
                    b.Navigation("RoutePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
